#!/bin/bash

# remove old files
rm -r svg/
mkdir svg/

# light

## modify colors
cat config.tex > light.tex

## run twice as sometimes this is needed to pickup certain things
lualatex light
lualatex light

## crop whitespace from pdf
## whitespace is originally included as some decorations are placed outside the
## main area by chemfig
pdfcrop --margins 0 light.pdf light.pdf

## break pdf into an svg for each page and output numbered
pdf2svg light.pdf %02d.svg all
mkdir svg/light/
mv *.svg svg/light/

# dark

## modify colors
cat config.tex |\
sed 's/black/temp/g' |\
sed 's/white/black/g' |\
sed 's/temp/white/g' \
> dark.tex

## run twice as sometimes this is needed to pickup certain things
lualatex dark
lualatex dark

## crop whitespace from pdf
## whitespace is originally included as some decorations are placed outside the
## main area by chemfig
pdfcrop --margins 0 dark.pdf dark.pdf

## break pdf into an svg for each page and output numbered
pdf2svg dark.pdf %02d.svg all
mkdir svg/dark/
mv *.svg svg/dark/

# cleanup
# keep light pdf for monitoring
rm *aux *log light.tex dark.tex dark.pdf
